### PR TITLE
Ported project to Python 3.x

### PR DESCRIPTION
**Pull request by jmarrec**
Also extended the test suite a bit.

### CODE REVIEW

**Comment by jayzeng** [comment]
Thanks for the pr, I will take a deeper look tonight

**Comment by jmarrec** [comment]
Jay, where you should mostly focus your reviewing efforts is as follows:

* Append the caching headers: I was getting an error because 'ETag' was `None`, so I included it in a if statement: https://github.com/jmarrec/walkscore/blob/walkscore_python3/walkscore/api.py#L65. I'm not 100% familiar with what caching headers really mean, so you should review that
* I don't know how you can distribute a py2 (yours) versus py3 (mine) version on pypi, so you should likely take a look at setup.py as well. I mean considering how small the code base is, it wouldn't be that hard to make a version that works on both py2 and py3 (handling imports with aliases) but that'll require extra time I don't really have.

**Comment by jayzeng** [comment]
Julien - the changes look good, I am going to merge it and hold on cutting a release as I want to make it compatible with Python 2.x.

**Comment by jayzeng** [comment]
@jmarrec merged, thanks for your contribution :)

**Pull request merged**
